# Generated by Django 3.1.7 on 2021-10-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productphoto',
            name='product_image',
        ),
        migrations.AddField(
            model_name='productphoto',
            name='product',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product'),
            preserve_default=False,
        ),
    ]
